type User {
  id: Int!
  name: String!
  email: String!
}
type Query {
  users: [User!]!
  user(id: Int!): User
}
input UserAdditionContent {
  name: String!
  email: String!
}
type Mutation {
  addUser(input: UserAdditionContent!): Int!
  removeUser(id: Int!): Boolean
  updateUser(id: Int!, input: UserAdditionContent!): User!
}
